info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2023-06-21T03:04:47.447Z"}
error: Could not connect to the database. connect ECONNREFUSED 127.0.0.1:27017 {"reason":{"commonWireVersion":null,"compatibilityError":null,"compatible":true,"heartbeatFrequencyMS":10000,"localThresholdMS":15,"logicalSessionTimeoutMinutes":null,"maxElectionId":null,"maxSetVersion":null,"servers":{},"setName":null,"stale":false,"type":"Single"},"stack":"MongooseServerSelectionError: connect ECONNREFUSED 127.0.0.1:27017\n    at NativeConnection.Connection.openUri (/home/akhil/CFP238/Fundoo_Note/FundooNote/node_modules/mongoose/lib/connection.js:847:32)\n    at /home/akhil/CFP238/Fundoo_Note/FundooNote/node_modules/mongoose/lib/index.js:351:10\n    at /home/akhil/CFP238/Fundoo_Note/FundooNote/node_modules/mongoose/lib/helpers/promiseOrCallback.js:32:5\n    at new Promise (<anonymous>)\n    at promiseOrCallback (/home/akhil/CFP238/Fundoo_Note/FundooNote/node_modules/mongoose/lib/helpers/promiseOrCallback.js:31:10)\n    at Mongoose._promiseOrCallback (/home/akhil/CFP238/Fundoo_Note/FundooNote/node_modules/mongoose/lib/index.js:1149:10)\n    at Mongoose.connect (/home/akhil/CFP238/Fundoo_Note/FundooNote/node_modules/mongoose/lib/index.js:350:20)\n    at _callee$ (/home/akhil/CFP238/Fundoo_Note/FundooNote/src/config/database.js:12:20)\n    at tryCatch (/home/akhil/CFP238/Fundoo_Note/FundooNote/node_modules/@babel/runtime/helpers/regeneratorRuntime.js:44:17)\n    at Generator.<anonymous> (/home/akhil/CFP238/Fundoo_Note/FundooNote/node_modules/@babel/runtime/helpers/regeneratorRuntime.js:125:22)\n    at Generator.next (/home/akhil/CFP238/Fundoo_Note/FundooNote/node_modules/@babel/runtime/helpers/regeneratorRuntime.js:69:21)\n    at asyncGeneratorStep (/home/akhil/CFP238/Fundoo_Note/FundooNote/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)\n    at _next (/home/akhil/CFP238/Fundoo_Note/FundooNote/node_modules/@babel/runtime/helpers/asyncToGenerator.js:22:9)\n    at /home/akhil/CFP238/Fundoo_Note/FundooNote/node_modules/@babel/runtime/helpers/asyncToGenerator.js:27:7\n    at new Promise (<anonymous>)\n    at /home/akhil/CFP238/Fundoo_Note/FundooNote/node_modules/@babel/runtime/helpers/asyncToGenerator.js:19:12","timestamp":"2023-06-21T03:05:17.454Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2023-06-21T03:21:18.434Z"}
error: Could not connect to the database. connect ECONNREFUSED 127.0.0.1:27017 {"reason":{"commonWireVersion":null,"compatibilityError":null,"compatible":true,"heartbeatFrequencyMS":10000,"localThresholdMS":15,"logicalSessionTimeoutMinutes":null,"maxElectionId":null,"maxSetVersion":null,"servers":{},"setName":null,"stale":false,"type":"Single"},"stack":"MongooseServerSelectionError: connect ECONNREFUSED 127.0.0.1:27017\n    at NativeConnection.Connection.openUri (/home/akhil/CFP238/Fundoo_Note/FundooNote/node_modules/mongoose/lib/connection.js:847:32)\n    at /home/akhil/CFP238/Fundoo_Note/FundooNote/node_modules/mongoose/lib/index.js:351:10\n    at /home/akhil/CFP238/Fundoo_Note/FundooNote/node_modules/mongoose/lib/helpers/promiseOrCallback.js:32:5\n    at new Promise (<anonymous>)\n    at promiseOrCallback (/home/akhil/CFP238/Fundoo_Note/FundooNote/node_modules/mongoose/lib/helpers/promiseOrCallback.js:31:10)\n    at Mongoose._promiseOrCallback (/home/akhil/CFP238/Fundoo_Note/FundooNote/node_modules/mongoose/lib/index.js:1149:10)\n    at Mongoose.connect (/home/akhil/CFP238/Fundoo_Note/FundooNote/node_modules/mongoose/lib/index.js:350:20)\n    at _callee$ (/home/akhil/CFP238/Fundoo_Note/FundooNote/src/config/database.js:12:20)\n    at tryCatch (/home/akhil/CFP238/Fundoo_Note/FundooNote/node_modules/@babel/runtime/helpers/regeneratorRuntime.js:44:17)\n    at Generator.<anonymous> (/home/akhil/CFP238/Fundoo_Note/FundooNote/node_modules/@babel/runtime/helpers/regeneratorRuntime.js:125:22)\n    at Generator.next (/home/akhil/CFP238/Fundoo_Note/FundooNote/node_modules/@babel/runtime/helpers/regeneratorRuntime.js:69:21)\n    at asyncGeneratorStep (/home/akhil/CFP238/Fundoo_Note/FundooNote/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)\n    at _next (/home/akhil/CFP238/Fundoo_Note/FundooNote/node_modules/@babel/runtime/helpers/asyncToGenerator.js:22:9)\n    at /home/akhil/CFP238/Fundoo_Note/FundooNote/node_modules/@babel/runtime/helpers/asyncToGenerator.js:27:7\n    at new Promise (<anonymous>)\n    at /home/akhil/CFP238/Fundoo_Note/FundooNote/node_modules/@babel/runtime/helpers/asyncToGenerator.js:19:12","timestamp":"2023-06-21T03:21:48.444Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2023-06-21T04:31:03.186Z"}
error: Could not connect to the database. connect ECONNREFUSED 127.0.0.1:27017 {"reason":{"commonWireVersion":null,"compatibilityError":null,"compatible":true,"heartbeatFrequencyMS":10000,"localThresholdMS":15,"logicalSessionTimeoutMinutes":null,"maxElectionId":null,"maxSetVersion":null,"servers":{},"setName":null,"stale":false,"type":"Single"},"stack":"MongooseServerSelectionError: connect ECONNREFUSED 127.0.0.1:27017\n    at NativeConnection.Connection.openUri (/home/akhil/CFP238/Fundoo_Note/FundooNote/node_modules/mongoose/lib/connection.js:847:32)\n    at /home/akhil/CFP238/Fundoo_Note/FundooNote/node_modules/mongoose/lib/index.js:351:10\n    at /home/akhil/CFP238/Fundoo_Note/FundooNote/node_modules/mongoose/lib/helpers/promiseOrCallback.js:32:5\n    at new Promise (<anonymous>)\n    at promiseOrCallback (/home/akhil/CFP238/Fundoo_Note/FundooNote/node_modules/mongoose/lib/helpers/promiseOrCallback.js:31:10)\n    at Mongoose._promiseOrCallback (/home/akhil/CFP238/Fundoo_Note/FundooNote/node_modules/mongoose/lib/index.js:1149:10)\n    at Mongoose.connect (/home/akhil/CFP238/Fundoo_Note/FundooNote/node_modules/mongoose/lib/index.js:350:20)\n    at _callee$ (/home/akhil/CFP238/Fundoo_Note/FundooNote/src/config/database.js:12:20)\n    at tryCatch (/home/akhil/CFP238/Fundoo_Note/FundooNote/node_modules/@babel/runtime/helpers/regeneratorRuntime.js:44:17)\n    at Generator.<anonymous> (/home/akhil/CFP238/Fundoo_Note/FundooNote/node_modules/@babel/runtime/helpers/regeneratorRuntime.js:125:22)\n    at Generator.next (/home/akhil/CFP238/Fundoo_Note/FundooNote/node_modules/@babel/runtime/helpers/regeneratorRuntime.js:69:21)\n    at asyncGeneratorStep (/home/akhil/CFP238/Fundoo_Note/FundooNote/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)\n    at _next (/home/akhil/CFP238/Fundoo_Note/FundooNote/node_modules/@babel/runtime/helpers/asyncToGenerator.js:22:9)\n    at /home/akhil/CFP238/Fundoo_Note/FundooNote/node_modules/@babel/runtime/helpers/asyncToGenerator.js:27:7\n    at new Promise (<anonymous>)\n    at /home/akhil/CFP238/Fundoo_Note/FundooNote/node_modules/@babel/runtime/helpers/asyncToGenerator.js:19:12","timestamp":"2023-06-21T04:31:33.196Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2023-06-21T04:33:46.511Z"}
error: Could not connect to the database. connect ECONNREFUSED 127.0.0.1:27017 {"reason":{"commonWireVersion":null,"compatibilityError":null,"compatible":true,"heartbeatFrequencyMS":10000,"localThresholdMS":15,"logicalSessionTimeoutMinutes":null,"maxElectionId":null,"maxSetVersion":null,"servers":{},"setName":null,"stale":false,"type":"Single"},"stack":"MongooseServerSelectionError: connect ECONNREFUSED 127.0.0.1:27017\n    at NativeConnection.Connection.openUri (/home/akhil/CFP238/Fundoo_Note/FundooNote/node_modules/mongoose/lib/connection.js:847:32)\n    at /home/akhil/CFP238/Fundoo_Note/FundooNote/node_modules/mongoose/lib/index.js:351:10\n    at /home/akhil/CFP238/Fundoo_Note/FundooNote/node_modules/mongoose/lib/helpers/promiseOrCallback.js:32:5\n    at new Promise (<anonymous>)\n    at promiseOrCallback (/home/akhil/CFP238/Fundoo_Note/FundooNote/node_modules/mongoose/lib/helpers/promiseOrCallback.js:31:10)\n    at Mongoose._promiseOrCallback (/home/akhil/CFP238/Fundoo_Note/FundooNote/node_modules/mongoose/lib/index.js:1149:10)\n    at Mongoose.connect (/home/akhil/CFP238/Fundoo_Note/FundooNote/node_modules/mongoose/lib/index.js:350:20)\n    at _callee$ (/home/akhil/CFP238/Fundoo_Note/FundooNote/src/config/database.js:12:20)\n    at tryCatch (/home/akhil/CFP238/Fundoo_Note/FundooNote/node_modules/@babel/runtime/helpers/regeneratorRuntime.js:44:17)\n    at Generator.<anonymous> (/home/akhil/CFP238/Fundoo_Note/FundooNote/node_modules/@babel/runtime/helpers/regeneratorRuntime.js:125:22)\n    at Generator.next (/home/akhil/CFP238/Fundoo_Note/FundooNote/node_modules/@babel/runtime/helpers/regeneratorRuntime.js:69:21)\n    at asyncGeneratorStep (/home/akhil/CFP238/Fundoo_Note/FundooNote/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)\n    at _next (/home/akhil/CFP238/Fundoo_Note/FundooNote/node_modules/@babel/runtime/helpers/asyncToGenerator.js:22:9)\n    at /home/akhil/CFP238/Fundoo_Note/FundooNote/node_modules/@babel/runtime/helpers/asyncToGenerator.js:27:7\n    at new Promise (<anonymous>)\n    at /home/akhil/CFP238/Fundoo_Note/FundooNote/node_modules/@babel/runtime/helpers/asyncToGenerator.js:19:12","timestamp":"2023-06-21T04:34:16.516Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2023-06-21T04:38:13.011Z"}
error: Could not connect to the database. connect ECONNREFUSED 127.0.0.1:27017 {"reason":{"commonWireVersion":null,"compatibilityError":null,"compatible":true,"heartbeatFrequencyMS":10000,"localThresholdMS":15,"logicalSessionTimeoutMinutes":null,"maxElectionId":null,"maxSetVersion":null,"servers":{},"setName":null,"stale":false,"type":"Single"},"stack":"MongooseServerSelectionError: connect ECONNREFUSED 127.0.0.1:27017\n    at NativeConnection.Connection.openUri (/home/akhil/CFP238/Fundoo_Note/FundooNote/node_modules/mongoose/lib/connection.js:847:32)\n    at /home/akhil/CFP238/Fundoo_Note/FundooNote/node_modules/mongoose/lib/index.js:351:10\n    at /home/akhil/CFP238/Fundoo_Note/FundooNote/node_modules/mongoose/lib/helpers/promiseOrCallback.js:32:5\n    at new Promise (<anonymous>)\n    at promiseOrCallback (/home/akhil/CFP238/Fundoo_Note/FundooNote/node_modules/mongoose/lib/helpers/promiseOrCallback.js:31:10)\n    at Mongoose._promiseOrCallback (/home/akhil/CFP238/Fundoo_Note/FundooNote/node_modules/mongoose/lib/index.js:1149:10)\n    at Mongoose.connect (/home/akhil/CFP238/Fundoo_Note/FundooNote/node_modules/mongoose/lib/index.js:350:20)\n    at _callee$ (/home/akhil/CFP238/Fundoo_Note/FundooNote/src/config/database.js:12:20)\n    at tryCatch (/home/akhil/CFP238/Fundoo_Note/FundooNote/node_modules/@babel/runtime/helpers/regeneratorRuntime.js:44:17)\n    at Generator.<anonymous> (/home/akhil/CFP238/Fundoo_Note/FundooNote/node_modules/@babel/runtime/helpers/regeneratorRuntime.js:125:22)\n    at Generator.next (/home/akhil/CFP238/Fundoo_Note/FundooNote/node_modules/@babel/runtime/helpers/regeneratorRuntime.js:69:21)\n    at asyncGeneratorStep (/home/akhil/CFP238/Fundoo_Note/FundooNote/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)\n    at _next (/home/akhil/CFP238/Fundoo_Note/FundooNote/node_modules/@babel/runtime/helpers/asyncToGenerator.js:22:9)\n    at /home/akhil/CFP238/Fundoo_Note/FundooNote/node_modules/@babel/runtime/helpers/asyncToGenerator.js:27:7\n    at new Promise (<anonymous>)\n    at /home/akhil/CFP238/Fundoo_Note/FundooNote/node_modules/@babel/runtime/helpers/asyncToGenerator.js:19:12","timestamp":"2023-06-21T04:38:43.020Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2023-06-21T04:40:11.904Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2023-06-21T04:40:54.310Z"}
error: Could not connect to the database. connect ECONNREFUSED 0.0.0.0:27017 {"reason":{"commonWireVersion":null,"compatibilityError":null,"compatible":true,"heartbeatFrequencyMS":10000,"localThresholdMS":15,"logicalSessionTimeoutMinutes":null,"maxElectionId":null,"maxSetVersion":null,"servers":{},"setName":null,"stale":false,"type":"Single"},"stack":"MongooseServerSelectionError: connect ECONNREFUSED 0.0.0.0:27017\n    at NativeConnection.Connection.openUri (/home/akhil/CFP238/Fundoo_Note/FundooNote/node_modules/mongoose/lib/connection.js:847:32)\n    at /home/akhil/CFP238/Fundoo_Note/FundooNote/node_modules/mongoose/lib/index.js:351:10\n    at /home/akhil/CFP238/Fundoo_Note/FundooNote/node_modules/mongoose/lib/helpers/promiseOrCallback.js:32:5\n    at new Promise (<anonymous>)\n    at promiseOrCallback (/home/akhil/CFP238/Fundoo_Note/FundooNote/node_modules/mongoose/lib/helpers/promiseOrCallback.js:31:10)\n    at Mongoose._promiseOrCallback (/home/akhil/CFP238/Fundoo_Note/FundooNote/node_modules/mongoose/lib/index.js:1149:10)\n    at Mongoose.connect (/home/akhil/CFP238/Fundoo_Note/FundooNote/node_modules/mongoose/lib/index.js:350:20)\n    at _callee$ (/home/akhil/CFP238/Fundoo_Note/FundooNote/src/config/database.js:12:20)\n    at tryCatch (/home/akhil/CFP238/Fundoo_Note/FundooNote/node_modules/@babel/runtime/helpers/regeneratorRuntime.js:44:17)\n    at Generator.<anonymous> (/home/akhil/CFP238/Fundoo_Note/FundooNote/node_modules/@babel/runtime/helpers/regeneratorRuntime.js:125:22)\n    at Generator.next (/home/akhil/CFP238/Fundoo_Note/FundooNote/node_modules/@babel/runtime/helpers/regeneratorRuntime.js:69:21)\n    at asyncGeneratorStep (/home/akhil/CFP238/Fundoo_Note/FundooNote/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)\n    at _next (/home/akhil/CFP238/Fundoo_Note/FundooNote/node_modules/@babel/runtime/helpers/asyncToGenerator.js:22:9)\n    at /home/akhil/CFP238/Fundoo_Note/FundooNote/node_modules/@babel/runtime/helpers/asyncToGenerator.js:27:7\n    at new Promise (<anonymous>)\n    at /home/akhil/CFP238/Fundoo_Note/FundooNote/node_modules/@babel/runtime/helpers/asyncToGenerator.js:19:12","timestamp":"2023-06-21T04:41:24.314Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2023-06-21T06:22:43.915Z"}
info: Connected to the database. {"timestamp":"2023-06-21T06:22:43.934Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2023-06-21T06:24:47.682Z"}
error: Could not connect to the database. Invalid message size: 1347703880, max allowed: 67108864 {"reason":{"commonWireVersion":null,"compatibilityError":null,"compatible":true,"heartbeatFrequencyMS":10000,"localThresholdMS":15,"logicalSessionTimeoutMinutes":null,"maxElectionId":null,"maxSetVersion":null,"servers":{},"setName":null,"stale":false,"type":"Single"},"stack":"MongooseServerSelectionError: Invalid message size: 1347703880, max allowed: 67108864\n    at NativeConnection.Connection.openUri (/home/akhil/CFP238/Fundoo_Note/FundooNote/node_modules/mongoose/lib/connection.js:847:32)\n    at /home/akhil/CFP238/Fundoo_Note/FundooNote/node_modules/mongoose/lib/index.js:351:10\n    at /home/akhil/CFP238/Fundoo_Note/FundooNote/node_modules/mongoose/lib/helpers/promiseOrCallback.js:32:5\n    at new Promise (<anonymous>)\n    at promiseOrCallback (/home/akhil/CFP238/Fundoo_Note/FundooNote/node_modules/mongoose/lib/helpers/promiseOrCallback.js:31:10)\n    at Mongoose._promiseOrCallback (/home/akhil/CFP238/Fundoo_Note/FundooNote/node_modules/mongoose/lib/index.js:1149:10)\n    at Mongoose.connect (/home/akhil/CFP238/Fundoo_Note/FundooNote/node_modules/mongoose/lib/index.js:350:20)\n    at _callee$ (/home/akhil/CFP238/Fundoo_Note/FundooNote/src/config/database.js:12:20)\n    at tryCatch (/home/akhil/CFP238/Fundoo_Note/FundooNote/node_modules/@babel/runtime/helpers/regeneratorRuntime.js:44:17)\n    at Generator.<anonymous> (/home/akhil/CFP238/Fundoo_Note/FundooNote/node_modules/@babel/runtime/helpers/regeneratorRuntime.js:125:22)\n    at Generator.next (/home/akhil/CFP238/Fundoo_Note/FundooNote/node_modules/@babel/runtime/helpers/regeneratorRuntime.js:69:21)\n    at asyncGeneratorStep (/home/akhil/CFP238/Fundoo_Note/FundooNote/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)\n    at _next (/home/akhil/CFP238/Fundoo_Note/FundooNote/node_modules/@babel/runtime/helpers/asyncToGenerator.js:22:9)\n    at /home/akhil/CFP238/Fundoo_Note/FundooNote/node_modules/@babel/runtime/helpers/asyncToGenerator.js:27:7\n    at new Promise (<anonymous>)\n    at /home/akhil/CFP238/Fundoo_Note/FundooNote/node_modules/@babel/runtime/helpers/asyncToGenerator.js:19:12","timestamp":"2023-06-21T06:25:17.690Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2023-06-21T06:25:40.644Z"}
info: Connected to the database. {"timestamp":"2023-06-21T06:25:40.664Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2023-06-21T06:28:08.186Z"}
info: Connected to the database. {"timestamp":"2023-06-21T06:28:08.228Z"}
error: 
    status - 500 
    message - ReferenceError: HttpStatus is not defined
    at newUserValidator (/home/akhil/CFP238/Fundoo_Note/FundooNote/src/validators/user.validator.js:12:16)
    at Layer.handle [as handle_request] (/home/akhil/CFP238/Fundoo_Note/FundooNote/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/akhil/CFP238/Fundoo_Note/FundooNote/node_modules/express/lib/router/route.js:144:13)
    at Route.dispatch (/home/akhil/CFP238/Fundoo_Note/FundooNote/node_modules/express/lib/router/route.js:114:3)
    at Layer.handle [as handle_request] (/home/akhil/CFP238/Fundoo_Note/FundooNote/node_modules/express/lib/router/layer.js:95:5)
    at /home/akhil/CFP238/Fundoo_Note/FundooNote/node_modules/express/lib/router/index.js:284:15
    at Function.process_params (/home/akhil/CFP238/Fundoo_Note/FundooNote/node_modules/express/lib/router/index.js:346:12)
    at next (/home/akhil/CFP238/Fundoo_Note/FundooNote/node_modules/express/lib/router/index.js:280:10)
    at Function.handle (/home/akhil/CFP238/Fundoo_Note/FundooNote/node_modules/express/lib/router/index.js:175:3)
    at router (/home/akhil/CFP238/Fundoo_Note/FundooNote/node_modules/express/lib/router/index.js:47:12)
    at Layer.handle [as handle_request] (/home/akhil/CFP238/Fundoo_Note/FundooNote/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/akhil/CFP238/Fundoo_Note/FundooNote/node_modules/express/lib/router/index.js:328:13)
    at /home/akhil/CFP238/Fundoo_Note/FundooNote/node_modules/express/lib/router/index.js:286:9
    at Function.process_params (/home/akhil/CFP238/Fundoo_Note/FundooNote/node_modules/express/lib/router/index.js:346:12)
    at next (/home/akhil/CFP238/Fundoo_Note/FundooNote/node_modules/express/lib/router/index.js:280:10)
    at Function.handle (/home/akhil/CFP238/Fundoo_Note/FundooNote/node_modules/express/lib/router/index.js:175:3) 
    url - /api/v1/users/ 
    method - POST 
    IP - ::1
   {"timestamp":"2023-06-21T06:30:09.540Z"}
error: 
    status - 500 
    message - ReferenceError: HttpStatus is not defined
    at newUserValidator (/home/akhil/CFP238/Fundoo_Note/FundooNote/src/validators/user.validator.js:12:16)
    at Layer.handle [as handle_request] (/home/akhil/CFP238/Fundoo_Note/FundooNote/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/akhil/CFP238/Fundoo_Note/FundooNote/node_modules/express/lib/router/route.js:144:13)
    at Route.dispatch (/home/akhil/CFP238/Fundoo_Note/FundooNote/node_modules/express/lib/router/route.js:114:3)
    at Layer.handle [as handle_request] (/home/akhil/CFP238/Fundoo_Note/FundooNote/node_modules/express/lib/router/layer.js:95:5)
    at /home/akhil/CFP238/Fundoo_Note/FundooNote/node_modules/express/lib/router/index.js:284:15
    at Function.process_params (/home/akhil/CFP238/Fundoo_Note/FundooNote/node_modules/express/lib/router/index.js:346:12)
    at next (/home/akhil/CFP238/Fundoo_Note/FundooNote/node_modules/express/lib/router/index.js:280:10)
    at Function.handle (/home/akhil/CFP238/Fundoo_Note/FundooNote/node_modules/express/lib/router/index.js:175:3)
    at router (/home/akhil/CFP238/Fundoo_Note/FundooNote/node_modules/express/lib/router/index.js:47:12)
    at Layer.handle [as handle_request] (/home/akhil/CFP238/Fundoo_Note/FundooNote/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/akhil/CFP238/Fundoo_Note/FundooNote/node_modules/express/lib/router/index.js:328:13)
    at /home/akhil/CFP238/Fundoo_Note/FundooNote/node_modules/express/lib/router/index.js:286:9
    at Function.process_params (/home/akhil/CFP238/Fundoo_Note/FundooNote/node_modules/express/lib/router/index.js:346:12)
    at next (/home/akhil/CFP238/Fundoo_Note/FundooNote/node_modules/express/lib/router/index.js:280:10)
    at Function.handle (/home/akhil/CFP238/Fundoo_Note/FundooNote/node_modules/express/lib/router/index.js:175:3) 
    url - /api/v1/users/ 
    method - POST 
    IP - ::1
   {"timestamp":"2023-06-21T06:32:01.327Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2023-06-21T06:35:03.167Z"}
error: Could not connect to the database. Invalid message size: 1347703880, max allowed: 67108864 {"reason":{"commonWireVersion":null,"compatibilityError":null,"compatible":true,"heartbeatFrequencyMS":10000,"localThresholdMS":15,"logicalSessionTimeoutMinutes":null,"maxElectionId":null,"maxSetVersion":null,"servers":{},"setName":null,"stale":false,"type":"Single"},"stack":"MongooseServerSelectionError: Invalid message size: 1347703880, max allowed: 67108864\n    at NativeConnection.Connection.openUri (/home/akhil/CFP238/Fundoo_Note/FundooNote/node_modules/mongoose/lib/connection.js:847:32)\n    at /home/akhil/CFP238/Fundoo_Note/FundooNote/node_modules/mongoose/lib/index.js:351:10\n    at /home/akhil/CFP238/Fundoo_Note/FundooNote/node_modules/mongoose/lib/helpers/promiseOrCallback.js:32:5\n    at new Promise (<anonymous>)\n    at promiseOrCallback (/home/akhil/CFP238/Fundoo_Note/FundooNote/node_modules/mongoose/lib/helpers/promiseOrCallback.js:31:10)\n    at Mongoose._promiseOrCallback (/home/akhil/CFP238/Fundoo_Note/FundooNote/node_modules/mongoose/lib/index.js:1149:10)\n    at Mongoose.connect (/home/akhil/CFP238/Fundoo_Note/FundooNote/node_modules/mongoose/lib/index.js:350:20)\n    at _callee$ (/home/akhil/CFP238/Fundoo_Note/FundooNote/src/config/database.js:12:20)\n    at tryCatch (/home/akhil/CFP238/Fundoo_Note/FundooNote/node_modules/@babel/runtime/helpers/regeneratorRuntime.js:44:17)\n    at Generator.<anonymous> (/home/akhil/CFP238/Fundoo_Note/FundooNote/node_modules/@babel/runtime/helpers/regeneratorRuntime.js:125:22)\n    at Generator.next (/home/akhil/CFP238/Fundoo_Note/FundooNote/node_modules/@babel/runtime/helpers/regeneratorRuntime.js:69:21)\n    at asyncGeneratorStep (/home/akhil/CFP238/Fundoo_Note/FundooNote/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)\n    at _next (/home/akhil/CFP238/Fundoo_Note/FundooNote/node_modules/@babel/runtime/helpers/asyncToGenerator.js:22:9)\n    at /home/akhil/CFP238/Fundoo_Note/FundooNote/node_modules/@babel/runtime/helpers/asyncToGenerator.js:27:7\n    at new Promise (<anonymous>)\n    at /home/akhil/CFP238/Fundoo_Note/FundooNote/node_modules/@babel/runtime/helpers/asyncToGenerator.js:19:12","timestamp":"2023-06-21T06:35:33.173Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2023-06-21T06:36:10.618Z"}
info: Connected to the database. {"timestamp":"2023-06-21T06:36:10.635Z"}
error: 
    status - 500 
    message - ReferenceError: HttpStatus is not defined
    at newUserValidator (/home/akhil/CFP238/Fundoo_Note/FundooNote/src/validators/user.validator.js:12:16)
    at Layer.handle [as handle_request] (/home/akhil/CFP238/Fundoo_Note/FundooNote/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/akhil/CFP238/Fundoo_Note/FundooNote/node_modules/express/lib/router/route.js:144:13)
    at Route.dispatch (/home/akhil/CFP238/Fundoo_Note/FundooNote/node_modules/express/lib/router/route.js:114:3)
    at Layer.handle [as handle_request] (/home/akhil/CFP238/Fundoo_Note/FundooNote/node_modules/express/lib/router/layer.js:95:5)
    at /home/akhil/CFP238/Fundoo_Note/FundooNote/node_modules/express/lib/router/index.js:284:15
    at Function.process_params (/home/akhil/CFP238/Fundoo_Note/FundooNote/node_modules/express/lib/router/index.js:346:12)
    at next (/home/akhil/CFP238/Fundoo_Note/FundooNote/node_modules/express/lib/router/index.js:280:10)
    at Function.handle (/home/akhil/CFP238/Fundoo_Note/FundooNote/node_modules/express/lib/router/index.js:175:3)
    at router (/home/akhil/CFP238/Fundoo_Note/FundooNote/node_modules/express/lib/router/index.js:47:12)
    at Layer.handle [as handle_request] (/home/akhil/CFP238/Fundoo_Note/FundooNote/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/akhil/CFP238/Fundoo_Note/FundooNote/node_modules/express/lib/router/index.js:328:13)
    at /home/akhil/CFP238/Fundoo_Note/FundooNote/node_modules/express/lib/router/index.js:286:9
    at Function.process_params (/home/akhil/CFP238/Fundoo_Note/FundooNote/node_modules/express/lib/router/index.js:346:12)
    at next (/home/akhil/CFP238/Fundoo_Note/FundooNote/node_modules/express/lib/router/index.js:280:10)
    at Function.handle (/home/akhil/CFP238/Fundoo_Note/FundooNote/node_modules/express/lib/router/index.js:175:3) 
    url - /api/v1/users/ 
    method - POST 
    IP - ::1
   {"timestamp":"2023-06-21T06:36:30.026Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2023-06-21T10:19:03.732Z"}
info: Connected to the database. {"timestamp":"2023-06-21T10:19:20.315Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2023-06-21T10:38:07.249Z"}
info: Connected to the database. {"timestamp":"2023-06-21T10:38:07.264Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2023-06-21T10:38:36.190Z"}
info: Connected to the database. {"timestamp":"2023-06-21T10:38:36.210Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2023-06-21T10:43:12.975Z"}
info: Connected to the database. {"timestamp":"2023-06-21T10:43:12.995Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2023-06-21T10:47:26.880Z"}
info: Connected to the database. {"timestamp":"2023-06-21T10:47:26.898Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2023-06-21T11:24:30.359Z"}
info: Connected to the database. {"timestamp":"2023-06-21T11:24:30.378Z"}
error: 
      status - 400
      message - Authorization token is required 
      url - /api/v1/users/login 
      method - POST 
      IP - ::1
     {"timestamp":"2023-06-21T11:24:59.429Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2023-06-21T12:15:01.048Z"}
info: Connected to the database. {"timestamp":"2023-06-21T12:15:01.078Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2023-06-21T12:15:07.633Z"}
info: Connected to the database. {"timestamp":"2023-06-21T12:15:07.672Z"}
error: 
    status - 500 
    message - JsonWebTokenError: invalid token
    at Object.verify (/home/akhil/CFP238/Fundoo_Note/FundooNote/node_modules/jsonwebtoken/verify.js:75:17)
    at _callee$ (/home/akhil/CFP238/Fundoo_Note/FundooNote/src/middlewares/auth.middleware.js:26:29)
    at tryCatch (/home/akhil/CFP238/Fundoo_Note/FundooNote/node_modules/@babel/runtime/helpers/regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (/home/akhil/CFP238/Fundoo_Note/FundooNote/node_modules/@babel/runtime/helpers/regeneratorRuntime.js:125:22)
    at Generator.next (/home/akhil/CFP238/Fundoo_Note/FundooNote/node_modules/@babel/runtime/helpers/regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (/home/akhil/CFP238/Fundoo_Note/FundooNote/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
    at _next (/home/akhil/CFP238/Fundoo_Note/FundooNote/node_modules/@babel/runtime/helpers/asyncToGenerator.js:22:9)
    at /home/akhil/CFP238/Fundoo_Note/FundooNote/node_modules/@babel/runtime/helpers/asyncToGenerator.js:27:7
    at new Promise (<anonymous>)
    at apply (/home/akhil/CFP238/Fundoo_Note/FundooNote/node_modules/@babel/runtime/helpers/asyncToGenerator.js:19:12)
    at userAuth (/home/akhil/CFP238/Fundoo_Note/FundooNote/src/middlewares/auth.middleware.js:15:22)
    at Layer.handle [as handle_request] (/home/akhil/CFP238/Fundoo_Note/FundooNote/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/akhil/CFP238/Fundoo_Note/FundooNote/node_modules/express/lib/router/route.js:144:13)
    at Route.dispatch (/home/akhil/CFP238/Fundoo_Note/FundooNote/node_modules/express/lib/router/route.js:114:3)
    at Layer.handle [as handle_request] (/home/akhil/CFP238/Fundoo_Note/FundooNote/node_modules/express/lib/router/layer.js:95:5)
    at /home/akhil/CFP238/Fundoo_Note/FundooNote/node_modules/express/lib/router/index.js:284:15 
    url - /api/v1/users/login 
    method - POST 
    IP - ::1
   {"timestamp":"2023-06-21T12:15:12.474Z"}
